exec-once = wl-clipboard-history -t
exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = systemctl --user start hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = systemctl start --user plasma-polkit-agent
exec-once = keepassxc --minimized
exec-once = hyprlauncher -d
exec-once = qbittorrent
exec-once = nicotine
#exec-once = easyeffects

# noctalia shell (use when battery life is not a problem)
# exec-once = qs -c noctalia-shell

# waybar apps turn off when using any shell
exec-once = hyprpaper
exec-once = waybar
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = kdeconnect-indicator
exec-once = swaync
