windowrule = match:title keepassxc, float on
windowrule = match:title file_progress, float on
windowrule = match:class file_progress, float on
windowrule = match:class splash, float on
windowrule = match:title dialog, float on
windowrule = match:class notification, float on
windowrule = match:title mpv, float on
windowrule = match:class download, float on
windowrule = match:class error, float on
windowrule = match:class splash, float on
windowrule = match:title Open File, float on
windowrule = match:title ^(Qalculate!)$, float on
windowrule = match:title (Qal)(.*), float on
windowrule = match:title (Pass)(*), float on
windowrule {
    name = Dekstop Fishes Fix
    match:class = steam_app_3618880
    match:title = Desktop Fishes
    float = true
    pin = true
    opacity = 0.9 override 0.9 override
    size = 400 600
    move = 100 100
}
